### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by tejpartapg** [cwizard2011/swagger-docs-tutorial#1]
@cwizard2011 would you be kind enough to share an example of how to use image upload with swagger-ui? In your opinion would a separate endpoint be created for image upload? 

Thank you

**Comment by cwizard2011** [comment]
This tutorial didn't cover image upload, but to upload image, it depends, you can have a separate endpoint for it. I think the best place to check it swagger documentation for more support on image upload. This tutorial only covers for splitting swagger docs into multiple file

**Comment by tejpartapg** [comment]
Thank you @cwizard2011 for replying to my query, I will look there as well.
